<?php
/** DevOne Apps Engine — multisite/network runtime. */
if (defined('DEVONE_APPS_LOADED')) { return; }
define('DEVONE_APPS_LOADED', true);
$GLOBALS['devone_app_manifests'] = $GLOBALS['devone_app_manifests'] ?? array();

function devone_app_slug($value,$fallback=''){ if(function_exists('devone_slugify'))return devone_slugify($value,$fallback);$v=strtolower(trim((string)$value));$v=trim(preg_replace('/[^a-z0-9_-]+/','-',$v),'-');return $v!==''?$v:$fallback; }
function devone_app_site_id(){ return function_exists('devone_content_site_id')?max(1,(int)devone_content_site_id()):1; }
function devone_app_is_super_admin(){ return function_exists('devone_network_is_super_admin')&&devone_network_is_super_admin(); }
function devone_app_base_path(){ $root=realpath(__DIR__.'/..')?:dirname(__DIR__);$base=$root.'/content/apps';if(!is_dir($base))@mkdir($base,0775,true);return realpath($base)?:$base; }
function devone_app_storage_base(){ $root=realpath(__DIR__.'/..')?:dirname(__DIR__);$base=$root.'/content/app-storage';if(!is_dir($base))@mkdir($base,0775,true);return realpath($base)?:$base; }
function devone_app_path_inside($path,$base){$rp=realpath($path);$rb=realpath($base);if(!$rp||!$rb)return false;$rp=str_replace('\\','/',$rp);$rb=rtrim(str_replace('\\','/',$rb),'/');return $rp===$rb||strpos($rp,$rb.'/')===0;}
function devone_app_root($folder){$folder=devone_app_slug($folder,'');if($folder==='')return '';$p=devone_app_base_path().DIRECTORY_SEPARATOR.$folder;return is_dir($p)&&devone_app_path_inside($p,devone_app_base_path())?(realpath($p)?:$p):'';}
function devone_app_manifest($folder,$refresh=false){$folder=devone_app_slug($folder,'');if($folder==='')return array();if(!$refresh&&isset($GLOBALS['devone_app_manifests'][$folder]))return $GLOBALS['devone_app_manifests'][$folder];$root=devone_app_root($folder);if($root===''||!is_file($root.'/app.json'))return array();$j=json_decode((string)@file_get_contents($root.'/app.json'),true);if(!is_array($j))return array();$m=array_merge(array('name'=>$folder,'slug'=>$folder,'version'=>'1.0.0','description'=>'','author'=>'','entry'=>'public/index.php','mount'=>'/apps/'.$folder,'capabilities'=>array(),'health'=>'','lifecycle'=>array()),$j);$m['folder']=$folder;$m['slug']=devone_app_slug($m['slug']??$folder,$folder);$m['name']=trim((string)$m['name'])?:$folder;$m['entry']=ltrim(str_replace('\\','/',(string)$m['entry']),'/');$mount='/'.trim((string)$m['mount'],'/');$m['mount']=$mount==='/'?'/apps/'.$folder:$mount;if(!is_array($m['capabilities']??null))$m['capabilities']=array();if(!is_array($m['lifecycle']??null))$m['lifecycle']=array();return $GLOBALS['devone_app_manifests'][$folder]=$m;}
function devone_app_resolve_file($folder,$relative,$mustExist=true){$root=devone_app_root($folder);if($root==='')return '';$relative=ltrim(str_replace('\\','/',trim((string)$relative)),'/');if($relative===''||strpos($relative,"\0")!==false||in_array('..',explode('/',$relative),true))return '';$path=$root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$relative);if($mustExist){$real=realpath($path);return($real&&is_file($real)&&devone_app_path_inside($real,$root))?$real:'';}$parent=realpath(dirname($path));return($parent&&devone_app_path_inside($parent,$root))?$path:'';}
function devone_app_validate($folder,&$error=''){$error='';if(devone_app_root($folder)===''){$error='App folder was not found.';return false;}$m=devone_app_manifest($folder,true);if(!$m){$error='app.json is missing or invalid.';return false;}if(devone_app_resolve_file($folder,$m['entry'])===''){$error='Declared app entry file was not found: '.$m['entry'];return false;}if(!preg_match('#^/[a-zA-Z0-9/_-]+$#',(string)$m['mount'])){$error='App mount contains unsupported characters.';return false;}return true;}
function devone_app_storage_path($folder,$siteId=null){$folder=devone_app_slug($folder,'');if($folder==='')return '';$siteId=$siteId===null?devone_app_site_id():max(0,(int)$siteId);$base=devone_app_storage_base();$path=$base.DIRECTORY_SEPARATOR.($siteId===0?'network':'site-'.$siteId).DIRECTORY_SEPARATOR.$folder;if(!is_dir($path))@mkdir($path,0775,true);return realpath($path)?:$path;}
function devone_app_upsert($folder,$manifest,$active=0,$status='installed',$error='',$siteId=null){if(!function_exists('table_exists')||!table_exists('apps'))return false;$siteId=$siteId===null?devone_app_site_id():max(0,(int)$siteId);$sql='INSERT INTO `'.table_name('apps').'` (`site_id`,`name`,`folder`,`version`,`description`,`mount_path`,`entry_file`,`capabilities`,`manifest`,`active`,`status`,`last_error`,`installed_at`,`updated_at`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`version`=VALUES(`version`),`description`=VALUES(`description`),`mount_path`=VALUES(`mount_path`),`entry_file`=VALUES(`entry_file`),`capabilities`=VALUES(`capabilities`),`manifest`=VALUES(`manifest`),`active`=VALUES(`active`),`status`=VALUES(`status`),`last_error`=VALUES(`last_error`),`updated_at`=CURRENT_TIMESTAMP';try{$s=db()->prepare($sql);return$s->execute(array($siteId,$manifest['name'],$folder,$manifest['version']??'1.0.0',$manifest['description']??'',$manifest['mount'],$manifest['entry'],json_encode($manifest['capabilities']),json_encode($manifest,JSON_UNESCAPED_SLASHES),$active,$status,$error));}catch(Throwable $e){return false;}}
function devone_app_set_state($folder,$active,$status,$error='',$siteId=null){$siteId=$siteId===null?devone_app_site_id():max(0,(int)$siteId);try{$s=db()->prepare('UPDATE `'.table_name('apps').'` SET active=?,status=?,last_error=?,updated_at=CURRENT_TIMESTAMP WHERE site_id=? AND folder=?');return$s->execute(array((int)$active,$status,$error,$siteId,$folder));}catch(Throwable $e){return false;}}
function devone_app_run_lifecycle($folder,$phase,$context=array(),&$error=''){$error='';$m=devone_app_manifest($folder,true);$rel=(string)($m['lifecycle'][$phase]??('lifecycle/'.$phase.'.php'));$file=devone_app_resolve_file($folder,$rel);if($file==='')return true;try{$devone_app_context=(array)$context;$devone_app_manifest=$m;$result=include$file;if($result===false){$error=ucfirst($phase).' routine returned false.';return false;}return true;}catch(Throwable $e){$error=$e->getMessage();return false;}}
function devone_app_sync_disk($siteId=null){if(!table_exists('apps'))return 0;$siteId=$siteId===null?devone_app_site_id():max(0,(int)$siteId);$count=0;foreach((array)glob(devone_app_base_path().'/*',GLOB_ONLYDIR)as$dir){$folder=basename($dir);$err='';if(devone_app_validate($folder,$err)){devone_app_upsert($folder,devone_app_manifest($folder,true),0,'installed','',$siteId);$count++;}}return$count;}
function devone_app_current_path(){$uri=parse_url((string)($_SERVER['REQUEST_URI']??'/'),PHP_URL_PATH);$base=parse_url(function_exists('devone_site_url')?devone_site_url(''):'/',PHP_URL_PATH);$path='/'.ltrim((string)$uri,'/');if($base&&$base!=='/'&&strpos($path,rtrim($base,'/'))===0)$path=substr($path,strlen(rtrim($base,'/')))?:'/';return'/'.ltrim($path,'/');}
function devone_app_match_active($path=null){if(!table_exists('apps'))return null;$path=$path?:devone_app_current_path();$siteId=devone_app_site_id();try{$s=db()->prepare('SELECT * FROM `'.table_name('apps').'` WHERE active=1 AND site_id IN (0,?) ORDER BY site_id DESC,LENGTH(mount_path) DESC');$s->execute(array($siteId));$rows=$s->fetchAll();}catch(Throwable $e){return null;}foreach($rows as$row){$mount='/'.trim((string)$row['mount_path'],'/');if($path===$mount||strpos($path,$mount.'/')===0)return$row;}return null;}
function devone_app_dispatch_request(){$row=devone_app_match_active();if(!$row)return false;$folder=(string)$row['folder'];$scopeId=(int)$row['site_id'];$err='';if(!devone_app_validate($folder,$err)){devone_app_set_state($folder,0,'error',$err,$scopeId);http_response_code(503);echo'App unavailable.';exit;}$m=devone_app_manifest($folder);$root=devone_app_root($folder);$entry=devone_app_resolve_file($folder,$m['entry']);$autoload=$root.'/vendor/autoload.php';if(is_file($autoload))require_once$autoload;$mount='/'.trim($m['mount'],'/');$requestPath=devone_app_current_path();$relative=substr($requestPath,strlen($mount));$relative=$relative===''?'/':'/'.ltrim($relative,'/');$devone_app=array('folder'=>$folder,'root'=>$root,'storage'=>devone_app_storage_path($folder,$scopeId===0?devone_app_site_id():$scopeId),'manifest'=>$m,'mount'=>$mount,'path'=>$relative,'site_id'=>devone_app_site_id(),'scope_site_id'=>$scopeId,'network_scope'=>$scopeId===0,'core'=>class_exists('DevOne')?DevOne::services():null);try{$result=include$entry;if(is_string($result))echo$result;}catch(Throwable $e){devone_app_set_state($folder,1,'error',$e->getMessage(),$scopeId);http_response_code(500);echo defined('DEV_MODE')&&DEV_MODE?'<pre>'.htmlspecialchars($e->getMessage()).'</pre>':'Application error.';}exit;}
final class DevOne_Apps_Service{public function all($siteId=null){$siteId=$siteId===null?devone_app_site_id():max(0,(int)$siteId);try{$s=db()->prepare('SELECT * FROM `'.table_name('apps').'` WHERE site_id=? ORDER BY name');$s->execute(array($siteId));return$s->fetchAll();}catch(Throwable $e){return array();}}public function find($folder,$siteId=null){$siteId=$siteId===null?devone_app_site_id():max(0,(int)$siteId);try{$s=db()->prepare('SELECT * FROM `'.table_name('apps').'` WHERE site_id=? AND folder=? LIMIT 1');$s->execute(array($siteId,devone_app_slug($folder,'')));return$s->fetch()?:null;}catch(Throwable $e){return null;}}public function manifest($folder){return devone_app_manifest($folder);}public function storage($folder,$siteId=null){return devone_app_storage_path($folder,$siteId);}public function match($path=null){return devone_app_match_active($path);}public function sync($siteId=null){return devone_app_sync_disk($siteId);}}
