<?php
require __DIR__ . '/includes/admin_common.php';
devone_require_permission('manage_dashboard');
verify_csrf();

$msg = $_GET['msg'] ?? '';
$root = realpath(__DIR__ . '/..') ?: dirname(__DIR__);
$currentUser = function_exists('devone_current_user') ? devone_current_user() : null;
$currentRole = strtolower((string)($currentUser['role'] ?? ''));
$isSubscriber = $currentRole === 'subscriber';
$canManageStore = function_exists('devone_has_permission') ? devone_has_permission('manage_store') : false;
$canManageBackups = function_exists('devone_has_permission') ? devone_has_permission('manage_backups') : false;
$canManageThemes = function_exists('devone_has_permission') ? devone_has_permission('manage_themes') : false;
$canManagePlugins = function_exists('devone_has_permission') ? devone_has_permission('manage_plugins') : false;
$canManageLibraries = function_exists('devone_has_permission') ? devone_has_permission('manage_libraries') : false;
$canManageScripts = function_exists('devone_has_permission') ? devone_has_permission('manage_settings') : false;
$canManagePages = function_exists('devone_has_permission') ? (devone_has_permission('create_pages') || devone_has_permission('edit_pages') || devone_has_permission('manage_pages')) : false;
$canUploadMedia = function_exists('devone_user_can_upload_media') ? devone_user_can_upload_media() : false;
$canUseScaffold = $canManagePlugins || $canManageThemes || (function_exists('devone_has_permission') && devone_has_permission('manage_modules'));

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'repair_home') {
    devone_require_permission('manage_settings');
    devone_seed_home_page();
    if (function_exists('devone_log')) { devone_log('system_repair', 'Home page repaired from dashboard'); }
    header('Location: dashboard.php?msg=' . rawurlencode('Homepage repaired. View Site should now load.'));
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'repair_schema') {
    devone_require_permission('manage_settings');
    $repair = devone_repair_core_schema(true);
    if (function_exists('devone_refresh_table_cache')) { devone_refresh_table_cache(); }
    if (function_exists('devone_log')) { devone_log('system_repair', 'Schema repair: ' . ($repair['message'] ?? '')); }
    header('Location: dashboard.php?msg=' . rawurlencode($repair['message'] ?? 'Schema repair complete.'));
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'repair_plugin_schemas') {
    devone_require_permission('manage_plugins');
    $results = function_exists('devone_repair_active_plugin_schemas') ? devone_repair_active_plugin_schemas() : array();
    $ok = count(array_filter($results)); $total = count($results);
    if (function_exists('devone_log')) { devone_log('plugin_schema_repair', 'Optimized plugin schemas repaired: ' . $ok . '/' . $total); }
    header('Location: dashboard.php?msg=' . rawurlencode('Plugin schema repair complete: ' . $ok . '/' . $total . ' optimized plugins succeeded.'));
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'make_scaffold') {
    if (!$canUseScaffold) { devone_require_permission('manage_plugins'); }
    $type = preg_replace('/[^a-z_\-]/', '', strtolower((string)($_POST['scaffold_type'] ?? 'plugin')));
    $name = trim((string)($_POST['scaffold_name'] ?? ''));
    $safeTitle = $name !== '' ? $name : 'My DevOne Item';
    $slug = function_exists('devone_slugify') ? devone_slugify($safeTitle, 'devone-item') : devone_slug($safeTitle);
    $created = false;
    $message = '';

    if ($type === 'plugin') {
        $dir = $root . '/content/plugins/' . $slug;
        @mkdir($dir, 0775, true);
        if (!is_file($dir . '/manifest.json')) {
            file_put_contents($dir . '/manifest.json', json_encode(array('name'=>$safeTitle,'slug'=>$slug,'version'=>'1.0.0','description'=>'Generated from DevOneCMS Dashboard.'), JSON_PRETTY_PRINT));
        }
        if (!is_file($dir . '/plugin.php')) {
            file_put_contents($dir . '/plugin.php', "<?php\n// {$safeTitle} plugin generated by DevOneCMS.\n\nif (function_exists('add_action')) {\n    // add_action('after_render', function () { });\n}\n");
        }
        $created = is_dir($dir);
        $message = $created ? 'Plugin scaffold created: ' . $slug : 'Could not create plugin scaffold.';
    } elseif ($type === 'theme') {
        $dir = $root . '/content/themes/' . $slug;
        @mkdir($dir, 0775, true);
        if (!is_file($dir . '/theme.json')) {
            file_put_contents($dir . '/theme.json', json_encode(array('name'=>$safeTitle,'slug'=>$slug,'version'=>'1.0.0','description'=>'Generated from DevOneCMS Dashboard.'), JSON_PRETTY_PRINT));
        }
        if (!is_file($dir . '/theme.css')) {
            file_put_contents($dir . '/theme.css', "/* {$safeTitle} generated by DevOneCMS */\n:root{--theme-accent:#27b7ff;}\nbody{font-family:Inter,system-ui,sans-serif;}\n");
        }
        $created = is_dir($dir);
        $message = $created ? 'Theme scaffold created: ' . $slug : 'Could not create theme scaffold.';
    } else {
        $moduleError = '';
        $moduleSlug = function_exists('devone_create_module_starter') ? devone_create_module_starter($safeTitle, 'Created from the DevOne CMS Dashboard.', $moduleError) : '';
        $created = $moduleSlug !== '';
        $message = $created ? 'Working module created: ' . $moduleSlug : ('Could not create module: ' . ($moduleError ?: 'module runtime unavailable.'));
    }

    if (function_exists('devone_log')) { devone_log('developer_package_created', $message); }
    header('Location: dashboard.php?msg=' . rawurlencode($message));
    exit;
}

function devone_count($table) {
    $tbl = function_exists('devone_require_table') ? devone_require_table($table, false) : (table_exists($table) ? table_name($table) : '');
    return $tbl !== '' ? (int)db()->query('SELECT COUNT(*) FROM `'.$tbl.'`')->fetchColumn() : 0;
}

function devone_bytes($bytes) {
    $bytes = (float)$bytes;
    $units = array('B','KB','MB','GB','TB');
    $i = 0;
    while ($bytes >= 1024 && $i < count($units)-1) { $bytes /= 1024; $i++; }
    return ($i === 0 ? number_format($bytes, 0) : number_format($bytes, 2)) . ' ' . $units[$i];
}

function devone_ini_bytes($value) {
    $value = trim((string)$value);
    if ($value === '' || $value === '-1') { return -1; }
    $num = (float)$value;
    $unit = strtolower(substr($value, -1));
    if ($unit === 'g') { $num *= 1024 * 1024 * 1024; }
    elseif ($unit === 'm') { $num *= 1024 * 1024; }
    elseif ($unit === 'k') { $num *= 1024; }
    return (int)$num;
}

function devone_total_ram() {
    if (@is_readable('/proc/meminfo')) {
        $meminfo = @file('/proc/meminfo');
        foreach ((array)$meminfo as $line) {
            if (stripos($line, 'MemTotal:') === 0 && preg_match('/\d+/', $line, $m)) {
                return ((int)$m[0]) * 1024;
            }
        }
    }
    if (stripos(PHP_OS_FAMILY, 'Windows') !== false && function_exists('shell_exec')) {
        $out = @shell_exec('wmic ComputerSystem get TotalPhysicalMemory /Value 2>NUL');
        if ($out && preg_match('/TotalPhysicalMemory=(\d+)/i', $out, $m)) { return (int)$m[1]; }
    }
    return null;
}

function devone_system_overview() {
    $root = realpath(__DIR__ . '/..') ?: dirname(__DIR__);
    $serverIp = $_SERVER['SERVER_ADDR'] ?? '';
    if ($serverIp === '') { $serverIp = gethostbyname(gethostname()); }
    $diskFree = @disk_free_space($root);
    $diskTotal = @disk_total_space($root);
    $ramTotal = devone_total_ram();
    $memLimit = devone_ini_bytes(ini_get('memory_limit'));
    $dbVersion = 'Unknown';
    try { $dbVersion = (string)db()->query('SELECT VERSION()')->fetchColumn(); } catch (Throwable $e) {}
    return array(
        'Server IP' => $serverIp ?: 'Unknown',
        'Operating System' => PHP_OS_FAMILY . ' / ' . php_uname('s') . ' ' . php_uname('r'),
        'Web Server' => $_SERVER['SERVER_SOFTWARE'] ?? 'Unknown',
        'PHP Version' => PHP_VERSION,
        'Database' => (defined('DB_NAME') ? DB_NAME : 'Unknown') . ' / ' . $dbVersion,
        'Active Theme' => function_exists('devone_theme') ? devone_theme() : get_setting('site_theme', 'devone-dark'),
        'Site URL' => defined('SITE_URL') ? SITE_URL : devone_site_url('/'),
        'Document Root' => $root,
        'Disk Free' => $diskFree !== false ? devone_bytes($diskFree) : 'Unknown',
        'Disk Total' => $diskTotal !== false ? devone_bytes($diskTotal) : 'Unknown',
        'Server RAM' => $ramTotal ? devone_bytes($ramTotal) : 'Unavailable on this host',
        'PHP Memory Limit' => $memLimit === -1 ? 'Unlimited' : devone_bytes($memLimit),
        'Upload Limit' => ini_get('upload_max_filesize') . ' / post ' . ini_get('post_max_size'),
    );
}

$report = function_exists('devone_table_resolver_report') ? devone_table_resolver_report() : array('configured_prefix'=>'cms_','active_prefix'=>'cms_','found'=>array(),'missing'=>array());
$checks = array(
    'Config file' => is_file(__DIR__ . '/../config.php'),
    'Configured prefix' => $report['configured_prefix'] ?? '',
    'Active detected prefix' => $report['active_prefix'] ?? '',
    'Pages table' => (function_exists('devone_require_table') ? devone_require_table('pages', true) !== '' : table_exists('pages')),
    'Home page published' => (bool)get_page('home'),
    'Theme folder' => is_dir(__DIR__ . '/../content/themes/' . devone_theme()),
    'Media writable' => is_writable(__DIR__ . '/../content/media') || @mkdir(__DIR__ . '/../content/media', 0775, true),
    'Backups writable' => is_writable(__DIR__ . '/../content/backups') || @mkdir(__DIR__ . '/../content/backups', 0775, true),
    'Libraries writable' => is_writable(__DIR__ . '/../content/libraries') || @mkdir(__DIR__ . '/../content/libraries', 0775, true),
    'Plugins writable' => is_writable(__DIR__ . '/../content/plugins') || @mkdir(__DIR__ . '/../content/plugins', 0775, true),
);

$counts = array(
    'Pages' => devone_count('pages'),
    'Media Files' => devone_count('media'),
    'Users' => devone_count('users'),
    'Plugins' => devone_count('plugins'),
    'Themes' => count(array_filter(glob(__DIR__ . '/../content/themes/*') ?: array(), 'is_dir')),
    'Libraries' => devone_count('libraries'),
);
$overview = devone_system_overview();
$backupCount = count(glob(__DIR__ . '/../content/backups/*.zip') ?: array());

devone_admin_header('Dashboard - DevOneCMS');
?>
<section class="admin-dashboard-hero">
  <div>
    <p class="admin-kicker"><span></span> DevOneCMS Control Center</p>
    <h1>Dashboard</h1>
    <p class="admin-hero-copy">Welcome back, Developer. Manage content, build features, check the system, build developer packages, and protect your install from one command-center view.</p>
  </div>
  <div class="admin-hero-actions">
    <a class="btn" href="../index.php" target="_blank" rel="noopener">View Site</a>
    <?php if (!$isSubscriber && $canManageStore): ?><a class="btn secondary" href="store.php">DevOne Store</a><?php endif; ?>
    <?php if (!$isSubscriber && $canManageBackups): ?><a class="btn secondary" href="backups.php">Backups</a><?php endif; ?>
  </div>
</section>

<?php devone_flash($msg); ?>

<section class="dashboard-stat-grid">
  <?php foreach ($counts as $label => $value): ?>
    <article class="dashboard-stat-card">
      <div class="stat-icon"><?= e(substr($label, 0, 1)) ?></div>
      <div><b><?= number_format((int)$value) ?></b><span><?= e($label) ?></span></div>
    </article>
  <?php endforeach; ?>
</section>

<section class="dashboard-two-col">
  <div class="card dashboard-quick-card">
    <div class="section-head"><h2>Quick Access</h2><span>Build faster</span></div>
    <div class="quick-access-grid">
      <?php if ($canManagePages): ?><a href="pages.php?action=new"><span>＋</span><strong>Add New Page</strong></a><?php endif; ?>
      <?php if ($canUploadMedia): ?><a href="media.php"><span>▧</span><strong>Upload Media</strong></a><?php endif; ?>
      <?php if ($canManageThemes): ?><a href="themes.php"><span>🎨</span><strong>Theme Manager</strong></a><?php endif; ?>
      <?php if ($canManagePlugins): ?><a href="plugins.php"><span>🧩</span><strong>Plugin Manager</strong></a><?php endif; ?>
      <?php if ($canManageLibraries): ?><a href="libraries.php"><span>⚡</span><strong>Library Manager</strong></a><?php endif; ?>
      <?php if ($canManageScripts): ?><a href="front-scripts.php"><span>{ }</span><strong>Front Scripts</strong></a><?php endif; ?>
      <?php if ($canManageBackups): ?><a href="backups.php"><span>↺</span><strong>Backup & Restore</strong></a><?php endif; ?>
      <?php if (!$canManagePages && !$canUploadMedia && !$canManageThemes && !$canManagePlugins && !$canManageLibraries && !$canManageScripts && !$canManageBackups): ?><a href="users.php?profile=me"><span>◎</span><strong>My Profile</strong></a><?php endif; ?>
    </div>
  </div>

  <div class="card dashboard-overview-card">
    <div class="section-head"><h2>System Overview</h2><span>Live install details</span></div>
    <div class="system-overview-list">
      <?php foreach ($overview as $label => $value): ?>
        <div><span><?= e($label) ?></span><strong><?= e($value) ?></strong></div>
      <?php endforeach; ?>
      <div><span>Local Backups</span><strong><?= number_format($backupCount) ?> archive<?= $backupCount === 1 ? '' : 's' ?></strong></div>
    </div>
  </div>
</section>

<section class="dashboard-two-col dashboard-lower-grid">
  <?php if ($canUseScaffold): ?>
  <div class="card dashboard-cli-card">
    <div class="section-head"><h2>Built-In CLI</h2><span>Developer commands</span></div>
    <div class="cli-terminal">
      <div><i>$</i> php devone make:plugin MyPlugin</div>
      <div><i>$</i> php devone make:theme MyTheme</div>
      <div><i>$</i> php devone make:module Blog</div>
      <div><i>$</i> php devone cache:clear</div>
    </div>
    <form method="post" class="scaffold-form">
      <?= csrf_field() ?>
      <input type="hidden" name="action" value="make_scaffold">
      <select name="scaffold_type">
        <option value="plugin">Plugin</option>
        <option value="theme">Theme</option>
        <option value="module">Working Module</option>
      </select>
      <input name="scaffold_name" placeholder="Name, example: Neon Slider">
      <button>Create Starter Package</button>
    </form>
  </div>
  <?php endif; ?>

  <?php if ($canManageBackups): ?>
  <div class="card dashboard-backup-card">
    <div class="section-head"><h2>Backup & Restore</h2><span>Protect the build</span></div>
    <p class="muted">Create a portable site backup with project files and a database SQL dump. Backups are stored in protected local storage and can be downloaded by authorized administrators.</p>
    <div class="backup-provider-grid">
      <span>Local ZIP</span><span>Google Drive</span><span>Amazon S3</span><span>Dropbox</span>
    </div>
    <p><a class="btn" href="backups.php">Open Backup Center</a></p>
  </div>
  <?php endif; ?>
</section>

<section class="card dashboard-check-card">
  <div class="section-head"><h2>System Check</h2><span>Core health</span></div>
  <table class="table"><tr><th>Check</th><th>Status</th></tr><?php foreach($checks as $label=>$ok): ?><tr><td><?= e($label) ?></td><td><?php if (is_bool($ok)) { echo $ok ? '✅ OK' : '⚠️ Needs attention'; } else { echo '<code>' . e($ok) . '</code>'; } ?></td></tr><?php endforeach; ?></table>
  <div class="inline-actions">
    <?php if (function_exists('devone_has_permission') && devone_has_permission('manage_settings')): ?>
    <form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="repair_schema"><button>Repair / Sync Core Tables</button></form>
    <form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="repair_plugin_schemas"><button>Repair / Sync Plugin Schemas</button></form>
    <?php if (empty($checks['Home page published'])): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="repair_home"><button>Repair Homepage</button></form><?php endif; ?>
    <?php endif; ?>
  </div>
  <?php if (!empty($report['resolved'])): ?><p><strong>Resolved tables:</strong> <code><?= e(json_encode($report['resolved'])) ?></code></p><?php endif; ?>
  <?php if (!empty($report['missing'])): ?><p><strong>Missing with active prefix:</strong> <code><?= e(implode(', ', $report['missing'])) ?></code></p><?php endif; ?>
</section>
<?php devone_admin_footer();
